    <?php echo $this->slider;?>   
    <?php //echo $this->math(4, 0, '/'); ?> 
        <div id="templatemo_main">
            <div class="col col23">
                <h2>Welcome To Beauty Class</h2>
                <p><em>Aenean rutrum, velit in tincidunt ullamcorper, augue arcu cursus tortor, a pulvinar urna eros ut dolor. In mollis augue non dolor faucibus et porta magna congue. </em></p>
                <p><a href="http://www.templatemo.com" target="_parent">Beauty Class</a> is free css template provided by <a href="http://www.templatemo.com" target="_parent">templatemo.com</a> for your personal or commercial websites. Vestibulum in mauris id nulla fermentum congue nec vel dolor. Duis ultricies, felis eget ornare adipiscing, erat libero iaculis metus, at suscipit metus erat viverra est. Etiam faucibus aliquet turpis sit amet congue. Praesent at nulla id lectus mattis consequat. Validate <a href="http://validator.w3.org/check?uri=referer" rel="nofollow"><strong>XHTML</strong></a> &amp; <a href="http://jigsaw.w3.org/css-validator/check/referer" rel="nofollow"><strong>CSS</strong></a>.</p>
                <div class="cleaner h40"></div>
                <?php if (count($this->data) > 0) :?>
                    <?php foreach ($this->data as $id => $val) :?>
                        <h3><?php echo $val['title']; ?></h3>
                        <img src="<?php echo $val['imageLink']; ?>" alt="" class="img_fl img_border" />
                        <h4><?php echo $val['subTitle']; ?></h4>
                        <p><?php echo $this->teaser($val['content'], 30); ?></p>
                        <a href="/blog/post/cid/<?php echo $val['id']; ?>">More</a>
                        <?php if (($id + 1) < count($this->data)) :?>
                        <div class="cleaner h40"></div>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
            <div class="col col13 no_margin_right">
                <h2>Services</h2>
                <p><em>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ut metus arcu, vitae congue purus.</em></p>
                <p>Sed massa lectus, pretium in consequat non, sagittis quis nisl. Aenean quis enim lorem. Cras bibendum magna quis urna dapibus convallis. Sed at lorem elit.</p>
                <ul class="tmo_ul_list">
                    <li class="first"><a href="#">Sed eget purus</a></li>
                    <li><a href="#">Vestibulum eleifend</a></li>
                    <li><a href="#">Nulla odio ipsum</a></li>
                    <li><a href="#">Suspendisse posuere</a></li>
                    <li><a href="#">Nunc a dui sed</a></li>
                    <li><a href="#">Curabitur ac mauris</a></li>
                    <li><a href="#">Mauris nulla tortor</a></li>
                    <li><a href="#">Nullam ultrices</a></li>
                </ul>
                <div class="cleaner h40"></div>
                <?php echo $this->newsLetter; ?>
            </div>
            <div class="cleaner"></div>
        </div>