        <div id="templatemo_slider">
           <div id="slider-wrapper">
                <div id="slider" class="nivoSlider">
                    <img src="/images/slider/01.jpg" alt="Slider 01" title="Phasellus lobortis malesuada luctus." />
                    <a href="#"><img src="images/slider/02.jpg" alt="Slider 02" title="Cras fringilla libero et lacus pellentesque mattis. " /></a>
                    <img src="/images/slider/03.jpg" alt="Slider 03" title="Proin vel dolor ut neque pulvinar laoreet sed blandit sapien." />
                    <img src="/images/slider/04.jpg" alt="Slider 04" title="Aenean sit amet turpis a ipsum vulputate laoreet non ac nisl." />
                    <img src="/images/slider/05.jpg" alt="Slider 05" title="Nunc nec elit sed libero rutrum ullamcorper et a lectus." />
                </div>
                <div id="htmlcaption" class="nivo-html-caption">
                    <strong>This</strong> is an example of a <em>HTML</em> caption with <a href="#">a link</a>.
                </div>
            </div>
            <script type="text/javascript">
            $(window).load(function() {
                $('#slider').nivoSlider();
            });
            </script>
        </div>