<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php echo $this->headTitle(); ?>
<meta name="keywords" content="beauty class, free theme, website design, bokehs, pink, orange, templatemo, CSS, HTML" />
<meta name="description" content="Beauty Class Theme, pinky background gradient with bokehs, free CSS template provided by templatemo.com" />
<!--link href="css/templatemo_style.css" rel="stylesheet" type="text/css" />

<link rel="stylesheet" href="css/nivo-slider.css" type="text/css" media="screen" />
<link rel="stylesheet" type="text/css" href="css/ddsmoothmenu.css" /-->
<?php 
	echo $this->headLink()->appendStylesheet('/css/templatemo_style.css')
							->appendStylesheet('/css/nivo-slider.css')
							->appendStylesheet('/css/slimbox2.css')
							->appendStylesheet('/css/ddsmoothmenu.css');
?>

<script language="javascript" type="text/javascript">
function clearText(field)
{
    if (field.defaultValue == field.value) field.value = '';
    else if (field.value == '') field.value = field.defaultValue;
}
</script>
<?php 
	echo $this->headScript()->appendFile('/js/jquery.min.js')
							->appendFile('/js/ddsmoothmenu.js')
							->appendFile('/js/jquery-1-4-2.min.js')
							->appendFile('/js/slimbox2.js')
							->appendFile('/js/jquery-1.4.3.min.js')
                            ->appendFile('/js/jquery.nivo.slider.pack.js');;
?>
<script type="text/javascript">

ddsmoothmenu.init({
	mainmenuid: "templatemo_menu", //menu DIV id
	orientation: 'h', //Horizontal or vertical menu: Set to "h" or "v"
	classname: 'ddsmoothmenu', //class added to menu's outer DIV
	//customtheme: ["#1c5a80", "#18374a"],
	contentsource: "markup" //"markup" or ["container_id", "path_to_menu_file"]
})

</script> 
</head>
<body>

<div id="templatemo_body_wrapper">
    <div id="templatemo_wrapper"><span id="templatemo_wrapper_top"></span>
        <div id="templatemo_header">    
            <div id="site_title"><a href="http://www.templatemo.com">Free CSS Templates</a></div>
            <div id="templatemo_menu" class="ddsmoothmenu">
                <ul>
                    <li><a href="/" class="selected">Home</a></li>
                    <li><a href="/about/">About</a>
                        <ul><li><span class="top"></span><span class="bottom"></span></li>
                            <li><a href="http://www.templatemo.com/page/1">Sub menu 1</a></li>
                            <li><a href="http://www.templatemo.com/page/2">Sub menu 2</a></li>
                            <li><a href="http://www.templatemo.com/page/3">Sub menu 3</a></li>
                      	</ul>
                    </li>
                    <li><a href="/gallery/">Gallery</a>
                        <ul><li><span class="top"></span><span class="bottom"></span></li>
                            <li><a href="http://www.templatemo.com/page/1">Sub menu 1</a></li>
                            <li><a href="http://www.templatemo.com/page/2">Sub menu 2</a></li>
                            <li><a href="http://www.templatemo.com/page/3">Sub menu 3</a></li>
                            <li><a href="http://www.templatemo.com/page/4">Sub menu 4</a></li>
                            <li><a href="http://www.templatemo.com/page/5">Sub menu 5</a></li>
                        </ul>
                    </li>
                    <li><a href="/blog/">Blog</a></li>
                    <li><a href="/contact/">Contact</a></li>
                </ul>
                <br style="clear: left" />
            </div> <!-- end of templatemo_menu -->
        </div>
<!-- slide and main -->
	<?php echo $this->layout()->content; ?>
    </div>
    <!-- template bootom -->
    <div id="templatemo_footer_wrapper">
        <div id="templatemo_footer">
            Copyright © 2048 <a href="#">Your Company Name</a> | Designed by <a href="http://www.templatemo.com" target="_parent">Free CSS Templates</a>
        </div>
    </div>
</div>
</body>
</html>