 <div id="templatemo_main">
            <h2>Contact Information</h2>
            <div class="col col23">
            	<h5>Send us a message now!</h5>
                Nam non auctor tortor. Maecenas vel leo at purus rhoncus aliquet a et tortor. Ut quis ipsum eu sem sollicitudin ultricies at in libero. Validate <a href="http://validator.w3.org/check?uri=referer" rel="nofollow"><strong>XHTML</strong></a> &amp; <a href="http://jigsaw.w3.org/css-validator/check/referer" rel="nofollow"><strong>CSS</strong></a>.
                 <div id="contact_form">
                       <form method="post" name="contact" action="#">
                            <p>
                                <?php
                                	echo $this->element->getElement('author');
                                ?>
                            </p>
                            <p>
                                <?php
                                	echo $this->element->getElement('email');
                                ?>
                            </p>
                            <p class="no_margin_right">
                                <?php
                                	echo $this->element->getElement('subject');
                                ?>
                            </p>
                            <div class="cleaner h20"></div>
                            <?php
                                	echo $this->element->getElement('message');
                                ?>
                            <div class="cleaner h20"></div>
                            <?php
                                	echo $this->element->getElement('reset');
                                ?>
							
                            <?php
                                	echo $this->element->getElement('submit');
                                ?>
                      </form>
                 </div>
            </div>
            
            <div class="col col13 no_margin_right">
            	<h4>Mailing Address</h4>
                <h6><strong>Company Name</strong></h6>
                    256-512 Pellentesque ut leo lectus,<br />
                    Tincidunt ut porttitor sit, 10770<br />
                    Facilisis vestibulum<br /><br />
                    
                <strong>Phone:</strong> 010-010-0110 <br />
                <strong>Email:</strong> <a href="mailto:info@company.com">info@company.com</a>  <br />
                <div class="cleaner h40"></div>
                
                <div class="img_border">
                <iframe width="270" height="270" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Central+Park,+New+York,+NY,+USA&amp;aq=0&amp;sll=14.093957,1.318359&amp;sspn=69.699334,135.263672&amp;vpsrc=6&amp;ie=UTF8&amp;hq=Central+Park,+New+York,+NY,+USA&amp;ll=40.778265,-73.96988&amp;spn=0.033797,0.06403&amp;t=m&amp;output=embed"></iframe>
            	</div>
                
            
        	</div>
			<div class="cleaner"></div>
    </div>